// ============================================================================
// Codes NAF (Rév. 2, 2008) — libellés pour les secteurs les plus fréquents
// Référentiel complet : https://www.insee.fr/fr/information/2406147
// ============================================================================

const NAF = {
    // A — Agriculture, sylviculture et pêche
    '01.11Z': "Culture de céréales",
    '01.13Z': "Culture de légumes",
    '01.21Z': "Culture de la vigne",
    '01.41Z': "Élevage de vaches laitières",
    '01.50Z': "Culture et élevage associés",
    '02.20Z': "Exploitation forestière",
    // C — Industrie manufacturière
    '10.13B': "Charcuterie",
    '10.71A': "Fabrication industrielle de pain",
    '10.71B': "Cuisson de produits de boulangerie",
    '10.71C': "Boulangerie et boulangerie-pâtisserie",
    '10.71D': "Pâtisserie",
    '10.85Z': "Fabrication de plats préparés",
    // F — Construction
    '41.10A': "Promotion immobilière de logements",
    '41.10B': "Promotion immobilière de bureaux",
    '41.10C': "Promotion immobilière d'autres bâtiments",
    '41.10D': "Supports juridiques de programmes",
    '41.20A': "Construction de maisons individuelles",
    '41.20B': "Construction d'autres bâtiments",
    '42.11Z': "Construction de routes et autoroutes",
    '42.99Z': "Construction d'autres ouvrages de génie civil",
    '43.11Z': "Travaux de démolition",
    '43.21A': "Travaux d'installation électrique",
    '43.22A': "Travaux d'installation d'eau et de gaz",
    '43.22B': "Travaux d'installation de plomberie",
    '43.31Z': "Travaux de plâtrerie",
    '43.32A': "Travaux de menuiserie bois et PVC",
    '43.33Z': "Travaux de revêtement des sols et des murs",
    '43.34Z': "Travaux de peinture et vitrerie",
    '43.39Z': "Autres travaux de finition",
    // G — Commerce ; réparation d'automobiles et de motocycles
    '45.11Z': "Commerce de voitures",
    '45.20A': "Entretien et réparation de véhicules",
    '46.19A': "Centrales d'achat non alimentaires",
    '46.21Z': "Commerce de gros de céréales",
    '46.38A': "Commerce de gros de poissons",
    '46.39A': "Commerce de gros alimentaire général",
    '46.73A': "Commerce de gros de bois",
    '47.11A': "Commerce de détail, épicerie",
    '47.11B': "Commerce de détail, supérette",
    '47.11C': "Supermarchés",
    '47.11D': "Supermarchés discount",
    '47.11E': "Magasins multi-commerces",
    '47.11F': "Hypermarchés",
    '47.19A': "Grands magasins",
    '47.19B': "Autres commerces non alimentaires",
    '47.21Z': "Commerce de détail de fruits et légumes",
    '47.22Z': "Commerce de détail de viandes",
    '47.23Z': "Commerce de détail de poissons",
    '47.24Z': "Commerce de détail de pain et pâtisserie",
    '47.25Z': "Commerce de détail de boissons",
    '47.26Z': "Commerce de détail de tabac",
    '47.41Z': "Commerce informatique",
    '47.42Z': "Commerce télécom",
    '47.43Z': "Commerce matériel audio-vidéo",
    '47.51Z': "Commerce textile",
    '47.52A': "Quincaillerie (< 400 m²)",
    '47.52B': "Quincaillerie (≥ 400 m²)",
    '47.53Z': "Commerce tapis, revêtements",
    '47.54Z': "Commerce électroménager",
    '47.71Z': "Commerce d'habillement",
    '47.72A': "Commerce de chaussures",
    '47.72B': "Commerce de maroquinerie",
    '47.73Z': "Pharmacie",
    '47.74Z': "Commerce articles médicaux",
    '47.75Z': "Commerce de parfumerie",
    '47.76Z': "Commerce de fleurs, animaux",
    '47.77Z': "Commerce d'horlogerie, bijouterie",
    '47.78A': "Commerce d'optique",
    '47.78B': "Commerce de charbons et combustibles",
    '47.78C': "Autres commerces spécialisés",
    '47.91A': "Vente à distance catalogue général",
    '47.91B': "Vente à distance catalogue spécialisé",
    // H — Transports
    '49.10Z': "Transport ferroviaire voyageurs",
    '49.31Z': "Transport urbain",
    '49.32Z': "Taxi",
    '49.41A': "Transport routier de marchandises",
    '49.41B': "Transport routier express",
    '49.42Z': "Déménagement",
    // I — Hébergement et restauration
    '55.10Z': "Hôtels",
    '55.20Z': "Hébergement de vacances",
    '55.30Z': "Camping",
    '55.90Z': "Autres hébergements",
    '56.10A': "Restauration traditionnelle",
    '56.10B': "Cafétérias",
    '56.10C': "Restauration de type rapide",
    '56.21Z': "Traiteur",
    '56.29A': "Restauration collective sous contrat",
    '56.29B': "Autres services de restauration",
    '56.30Z': "Débits de boissons",
    // J — Information et communication
    '58.21Z': "Édition de jeux électroniques",
    '58.29A': "Édition de logiciels système",
    '58.29B': "Édition de logiciels grand public",
    '58.29C': "Édition de logiciels applicatifs",
    '59.11A': "Production de films cinématographiques",
    '59.11B': "Production de films institutionnels",
    '62.01Z': "Programmation informatique",
    '62.02A': "Conseil en systèmes informatiques",
    '62.02B': "Tierce maintenance de systèmes",
    '62.03Z': "Gestion d'installations informatiques",
    '62.09Z': "Autres activités informatiques",
    '63.11Z': "Traitement de données, hébergement",
    '63.12Z': "Portails internet",
    // K — Activités financières et d'assurance
    '64.19Z': "Banques",
    '64.20Z': "Holdings (sociétés holding)",
    '64.30Z': "Fonds de placement",
    '66.19A': "Support aux activités financières",
    '66.19B': "Autres auxiliaires des services financiers",
    '66.22Z': "Activités des agents d'assurances",
    // L — Activités immobilières
    '68.10Z': "Achat-vente de biens immobiliers",
    '68.20A': "Location de logements",
    '68.20B': "Location de biens immobiliers",
    '68.31Z': "Agences immobilières",
    '68.32A': "Administration d'immeubles résidentiels",
    '68.32B': "Autres supports juridiques",
    // M — Activités spécialisées, scientifiques et techniques
    '69.10Z': "Activités juridiques",
    '69.20Z': "Activités comptables",
    '70.10Z': "Activités des sièges sociaux",
    '70.21Z': "Relations publiques et communication",
    '70.22Z': "Conseil pour les affaires",
    '71.11Z': "Architecture",
    '71.12A': "Activité des géomètres",
    '71.12B': "Ingénierie, études techniques",
    '72.19Z': "Recherche en sciences physiques",
    '73.11Z': "Activités des agences de publicité",
    '73.12Z': "Régie publicitaire de médias",
    '73.20Z': "Études de marché et sondages",
    '74.10Z': "Activités spécialisées de design",
    '74.20Z': "Activités photographiques",
    '74.30Z': "Traduction et interprétation",
    '74.90A': "Activité d'intermédiaires en commerce",
    '74.90B': "Autres activités scientifiques",
    // N — Activités de services administratifs et de soutien
    '77.11A': "Location de véhicules automobiles",
    '77.21Z': "Location articles de loisirs",
    '78.10Z': "Activités des agences de placement",
    '78.20Z': "Travail temporaire",
    '79.11Z': "Agences de voyage",
    '79.90Z': "Autres services de réservation",
    '81.10Z': "Activités combinées de soutien",
    '81.21Z': "Nettoyage courant des bâtiments",
    '81.22Z': "Autres activités de nettoyage",
    // P — Enseignement
    '85.51Z': "Enseignement de disciplines sportives",
    '85.59A': "Formation continue d'adultes",
    '85.59B': "Autres enseignements",
    '85.60Z': "Activités de soutien à l'enseignement",
    // Q — Santé humaine et action sociale
    '86.10Z': "Hôpitaux",
    '86.21Z': "Activité des médecins généralistes",
    '86.22A': "Activité des médecins spécialistes libéraux",
    '86.22B': "Activité des médecins spécialistes en cliniques",
    '86.23Z': "Pratique dentaire",
    '86.90A': "Laboratoires d'analyses médicales",
    '86.90D': "Activité des infirmiers",
    '86.90E': "Activité des kinésithérapeutes",
    '86.90F': "Activité des orthophonistes",
    '87.10A': "Hébergement médicalisé pour personnes âgées",
    '88.10A': "Aide à domicile",
    // R — Arts, spectacles et activités récréatives
    '90.01Z': "Arts du spectacle vivant",
    '90.02Z': "Activités de soutien au spectacle vivant",
    '93.11Z': "Gestion d'installations sportives",
    '93.12Z': "Activités de clubs de sports",
    '93.13Z': "Activités des salles de fitness",
    // S — Autres activités de services
    '96.01A': "Blanchisserie-teinturerie",
    '96.02A': "Coiffure",
    '96.02B': "Soins de beauté",
    '96.04Z': "Entretien corporel"
};

// Renvoie le libellé NAF pour un code, ou null
export function libelleNAF(code) {
    if (!code) return null;
    const k = String(code).toUpperCase();
    return NAF[k] || null;
}
